package sk.upjs.ics.autobazar.GUI;

import java.io.File;
import java.time.Instant;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import sk.upjs.ics.autobazar.InzeratFactory;
import sk.upjs.ics.autobazar.InzeratMotocykel;
import sk.upjs.ics.autobazar.InzeratMotocykelDao;
/**
 *
 * @author PC
 */
public class PridatMotocykelForm extends javax.swing.JDialog {
    private Long idP = null;
    
    private InzeratMotocykelDao inzeratDao3 = InzeratFactory.INSTANCE.getInzeratMotocykelDao();
    /**
     * Creates new form PridatMotocykelForm
     */
    public PridatMotocykelForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public PridatMotocykelForm(java.awt.Frame parent, boolean modal,Long idP) {
        super(parent, modal);
        initComponents();        
        this.idP=idP;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spatButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        znackaLabel = new javax.swing.JLabel();
        znackaTextField = new javax.swing.JTextField();
        modelTextField = new javax.swing.JTextField();
        modelLabel = new javax.swing.JLabel();
        rocnikTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        objemTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        kmTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        prevodovkaTextField = new javax.swing.JTextField();
        prevodovkaLabel = new javax.swing.JLabel();
        vykonTextField = new javax.swing.JTextField();
        vykonLabel = new javax.swing.JLabel();
        cenaTextField = new javax.swing.JTextField();
        cenaLabel = new javax.swing.JLabel();
        obrazokTextField = new javax.swing.JTextField();
        pridatObrazokButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        spatButton.setText("Spat");
        spatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spatButtonActionPerformed(evt);
            }
        });

        okButton.setText("Ok");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        znackaLabel.setText("Znacka:");

        modelLabel.setText("Model:");

        jLabel1.setText("Rocnik:");

        jLabel2.setText("Objem:");

        jLabel3.setText("Km:");

        prevodovkaLabel.setText("Prevodovka:");

        vykonLabel.setText("Vykon:");

        cenaLabel.setText("Cena:");

        pridatObrazokButton2.setText("Pridat obrázok");
        pridatObrazokButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridatObrazokButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(znackaLabel)
                .addGap(32, 32, 32)
                .addComponent(znackaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(prevodovkaLabel)
                .addGap(19, 19, 19)
                .addComponent(prevodovkaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(modelLabel)
                .addGap(38, 38, 38)
                .addComponent(modelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(vykonLabel)
                .addGap(47, 47, 47)
                .addComponent(vykonTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(rocnikTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(35, 35, 35)
                .addComponent(objemTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(cenaLabel)
                .addGap(51, 51, 51)
                .addComponent(cenaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(52, 52, 52)
                .addComponent(kmTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(obrazokTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(pridatObrazokButton2)
                .addGap(231, 231, 231)
                .addComponent(okButton)
                .addGap(15, 15, 15)
                .addComponent(spatButton))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(znackaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prevodovkaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(znackaLabel)
                            .addComponent(prevodovkaLabel))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vykonTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modelLabel)
                            .addComponent(vykonLabel))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addComponent(rocnikTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(objemTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(cenaLabel))
                    .addComponent(cenaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addComponent(kmTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(obrazokTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pridatObrazokButton2)
                    .addComponent(okButton)
                    .addComponent(spatButton)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spatButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_spatButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        InzeratMotocykel i = new InzeratMotocykel();
        Long value = null;
        if (znackaTextField.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "Nezadali ste znacku.");
            return;
        }
        i.setZnacka(znackaTextField.getText());
        
        if (modelTextField.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "Nezadali ste model.");
            return;
        }
        i.setModel(modelTextField.getText());
        
        if (rocnikTextField.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "Nezadali ste rocnik.");
            return;
        }
        i.setRocnik(rocnikTextField.getText());
        
        if (objemTextField.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "Nezadali ste objem.");
            return;
        }
        value = Long.parseLong(objemTextField.getText());
        i.setObjem(value);
        
        if (kmTextField.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "Nezadali ste pocet kilometrov.");
            return;
        }
        value = Long.parseLong(kmTextField.getText());
        i.setKm(value);
        
        if (prevodovkaTextField.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "Nezadali ste typ prevodovky.");
            return;
        }
        i.setPrevodovka(prevodovkaTextField.getText());
        
        if (vykonTextField.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "Nezadali ste vykon.");
            return;
        }
        value = Long.parseLong(vykonTextField.getText());
        i.setVykon(value);
        
        if (cenaTextField.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "Nezadali ste cenu.");
            return;
        }
        value = Long.parseLong(cenaTextField.getText());
        i.setCena(value);
        i.setDatumPridania(Date.from(Instant.now()));
        i.setIdP(idP);
        
        inzeratDao3.pridat(i);
        setVisible(false);
    }//GEN-LAST:event_okButtonActionPerformed

    private void pridatObrazokButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridatObrazokButton2ActionPerformed
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files", "jpg", "png", "gif", "jpeg");
        final JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        chooser.setFileFilter(filter);
        chooser.setAcceptAllFileFilterUsed(false);
        chooser.showOpenDialog(this);
        if (chooser.getSelectedFile() != null) {
            obrazokTextField.setText(chooser.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_pridatObrazokButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PridatMotocykelForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PridatMotocykelForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PridatMotocykelForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PridatMotocykelForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PridatMotocykelForm dialog = new PridatMotocykelForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cenaLabel;
    private javax.swing.JTextField cenaTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField kmTextField;
    private javax.swing.JLabel modelLabel;
    private javax.swing.JTextField modelTextField;
    private javax.swing.JTextField objemTextField;
    private javax.swing.JTextField obrazokTextField;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel prevodovkaLabel;
    private javax.swing.JTextField prevodovkaTextField;
    private javax.swing.JButton pridatObrazokButton;
    private javax.swing.JButton pridatObrazokButton1;
    private javax.swing.JButton pridatObrazokButton2;
    private javax.swing.JTextField rocnikTextField;
    private javax.swing.JButton spatButton;
    private javax.swing.JLabel vykonLabel;
    private javax.swing.JTextField vykonTextField;
    private javax.swing.JLabel znackaLabel;
    private javax.swing.JTextField znackaTextField;
    // End of variables declaration//GEN-END:variables
}
